apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opendkim.fullname" . }}-tables
  labels:
    {{- include "opendkim.labels" . | nindent 4 }}
{{- $domains := include "opendkim.domains" . | fromJsonArray }}
data:
  TrustedHosts: |
{{- range .Values.trustedHosts.defaults }}
    {{ . }}
{{- end }}
{{- range .Values.trustedHosts.additional }}
    {{ . }}
{{- end }}
{{- range $domains }}
    {{ .domain }}
    *.{{ .domain }}
{{- end }}

  SigningTable: |
{{- range $domains }}
    *@{{ .domain }} {{ default "mail" .dkimSelector }}._domainkey.{{ .domain }}
    *@*.{{ .domain }} {{ default "mail" .dkimSelector }}._domainkey.{{ .domain }}
{{- end }}

  KeyTable: |
{{- range $domains }}
    {{ default "mail" .dkimSelector }}._domainkey.{{ .domain }} {{ .domain }}:{{ default "mail" .dkimSelector }}:/etc/dkimkeys/{{ .domain }}/{{ default "mail" .dkimSelector }}.private
{{- end }}
