apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opendkim.fullname" . }}-config
  labels:
    {{- include "opendkim.labels" . | nindent 4 }}
data:
  opendkim.conf: |
{{ .Values.opendkimConf | indent 4 }}
