{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "opendkim.serviceName" . }}
  labels:
    {{- include "opendkim.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: opendkim
      protocol: TCP
      name: opendkim
  selector:
    {{- include "opendkim.selectorLabels" . | nindent 4 }}
{{- end }}
