apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postfix.fullname" . }}
  labels:
    {{- include "postfix.labels" . | nindent 4 }}
data:
  main.cf: |
{{ tpl (.Files.Get "files/postfix/main.cf") . | indent 4 }}
  master.cf: |
{{ tpl (.Files.Get "files/postfix/master.cf") . | indent 4 }}
  silver.yaml: |
    domains:
      - domain: {{ include "opengovmail.domain" . }}
