apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rspamd.fullname" . }}-config-static
  labels:
    {{- include "rspamd.labels" . | nindent 4 }}
data:
  antivirus.conf: |
    clamav {
      type = "clamav";
      servers = "{{ .Values.dependencies.clamav.host }}:{{ .Values.dependencies.clamav.port }}";
      action = "{{ .Values.modules.antivirus.clamav_action }}";
      symbol = "CLAM_VIRUS";
      log_clean = true;
    }

  classifier-bayes.conf: |
    backend = "{{ .Values.modules.classifier_bayes.backend }}";
    new_schema = true;
    expire = 8640000;

    autolearn {
      spam_threshold = {{ .Values.modules.classifier_bayes.spam_threshold }};
      ham_threshold = {{ .Values.modules.classifier_bayes.ham_threshold }};
      check_balance = true;
    }

  milter_headers.conf: |
    extended_headers_enabled = true;
    use_mailbox = false;

  metrics_exporter.conf: |
    enabled = {{ if .Values.modules.metrics_exporter.enabled }}true{{ else }}false{{ end }};

  worker-proxy.inc: |
    bind = "*:{{ .Values.service.milter.port }}";
    protocol = "milter";
